import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

/// Model for ProductDetails from Supabase
class ProductDetails {
  final int id;
  final String identityId;
  final DateTime createdAt;
  final int quantity;
  final String unit;
  final double price;
  final String supplier;
  final DateTime expireDate;

  ProductDetails({
    required this.id,
    required this.identityId,
    required this.createdAt,
    required this.quantity,
    required this.unit,
    required this.price,
    required this.supplier,
    required this.expireDate,
  });

  factory ProductDetails.fromJson(Map<String, dynamic> json) {
    return ProductDetails(
      id: json['id'] as int,
      identityId: json['identity_id'] as String,
      createdAt: DateTime.parse(json['created_at'] as String),
      quantity: json['quantity'] as int,
      unit: json['unit'] as String,
      price:
          (json['price'] is int)
              ? (json['price'] as int).toDouble()
              : double.tryParse(json['price'].toString()) ?? 0.0,
      supplier: json['supplier'] as String,
      expireDate: DateTime.parse(json['expire_date'] as String),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'identity_id': identityId,
      'created_at': createdAt.toIso8601String(),
      'quantity': quantity,
      'unit': unit,
      'price': price,
      'supplier': supplier,
      'expire_date': expireDate.toIso8601String().split('T')[0], // Date only
    };
  }

  @override
  String toString() {
    return 'ProductDetails(id: $id, identityId: $identityId, quantity: $quantity, unit: $unit, price: $price, supplier: $supplier, expireDate: $expireDate)';
  }
}

/// Service class to handle ProductDetails operations with Supabase
class ProductDetailsService {
  static final SupabaseClient _supabase = Supabase.instance.client;
  static const String _tableName = 'products_details';

  /// Fetch product details by composite ID (productId-uPriceId)
  static Future<List<ProductDetails>> getProductDetailsByCompositeId(
    String compositeId,
  ) async {
    try {
      print('Fetching product details for composite ID: $compositeId');

      final response = await _supabase
          .from(_tableName)
          .select()
          .eq('identity_id', compositeId)
          .order('created_at', ascending: true);

      if (response.isEmpty) {
        print('No product details found for identity_id: $compositeId');
        return [];
      }

      final List<ProductDetails> productDetailsList =
          (response as List)
              .map((item) => ProductDetails.fromJson(item))
              .toList();

      print(
        'Found ${productDetailsList.length} product details for identity_id: $compositeId',
      );
      return productDetailsList;
    } catch (error) {
      print('Error fetching product details: $error');
      throw Exception('Failed to fetch product details: $error');
    }
  }

  /// Fetch all product details for a given product ID
  static Future<List<ProductDetails>> getAllProductDetailsByProductId(
    int productId,
  ) async {
    try {
      print('Fetching all product details for product ID: $productId');

      // Use LIKE query to find all records starting with productId-
      final response = await _supabase
          .from(_tableName)
          .select()
          .like('identity_id', '$productId-%')
          .order('created_at', ascending: true);

      if (response.isEmpty) {
        print('No product details found for product ID: $productId');
        return [];
      }

      final List<ProductDetails> productDetailsList =
          (response as List)
              .map((item) => ProductDetails.fromJson(item))
              .toList();

      print(
        'Found ${productDetailsList.length} product details for product ID: $productId',
      );
      return productDetailsList;
    } catch (error) {
      print('Error fetching product details: $error');
      throw Exception('Failed to fetch product details: $error');
    }
  }

  /// Create a new product detail
  static Future<ProductDetails> createProductDetail(
    ProductDetails productDetail,
  ) async {
    try {
      // Create a copy of the JSON data without the id field for creation
      final jsonData = productDetail.toJson();
      jsonData.remove(
        'id',
      ); // Remove id field since it's auto-generated by backend

      print('Creating product detail: $jsonData');

      final response =
          await _supabase.from(_tableName).insert(jsonData).select().single();

      final createdProductDetail = ProductDetails.fromJson(response);
      print('Product detail created successfully: ${createdProductDetail.id}');
      return createdProductDetail;
    } catch (error) {
      print('Error creating product detail: $error');
      throw Exception('Failed to create product detail: $error');
    }
  }

  /// Update an existing product detail
  static Future<ProductDetails> updateProductDetail(
    ProductDetails productDetail,
  ) async {
    try {
      print('Updating product detail with ID: ${productDetail.id}');

      final response =
          await _supabase
              .from(_tableName)
              .update(productDetail.toJson())
              .eq('id', productDetail.id)
              .select()
              .single();

      final updatedProductDetail = ProductDetails.fromJson(response);
      print('Product detail updated successfully: ${updatedProductDetail.id}');
      return updatedProductDetail;
    } catch (error) {
      print('Error updating product detail: $error');
      throw Exception('Failed to update product detail: $error');
    }
  }

  /// Delete a product detail by its unique ID
  static Future<void> deleteProductDetail(int id) async {
    try {
      print('Deleting product detail with ID: $id');

      await _supabase.from(_tableName).delete().eq('id', id);

      print('Product detail deleted successfully: $id');
    } catch (error) {
      print('Error deleting product detail: $error');
      throw Exception('Failed to delete product detail: $error');
    }
  }

  /// Generate composite ID from product ID and uPrice ID
  static String generateCompositeId(int productId, String uPriceId) {
    return '$productId-$uPriceId';
  }

  /// Parse composite ID to get product ID and uPrice ID
  static Map<String, dynamic> parseCompositeId(String compositeId) {
    final parts = compositeId.split('-');
    if (parts.length != 2) {
      throw ArgumentError(
        'Invalid composite ID format. Expected: productId-uPriceId',
      );
    }

    return {'productId': int.tryParse(parts[0]), 'uPriceId': parts[1]};
  }

  /// Check if any product details exist for a given product ID
  static Future<bool> hasProductDetailsForProductId(int productId) async {
    try {
      final response = await _supabase
          .from(_tableName)
          .select('id')
          .like('identity_id', '$productId-%')
          .limit(1);

      return response.isNotEmpty;
    } catch (error) {
      print('Error checking product details existence: $error');
      return false;
    }
  }

  /// Add stock type attribute to a specific uPrice element
  static Future<void> addStockTypeToProduct(
    int productId,
    String uPriceId,
    String stockType, // 'global_stock' or 'sole_stock'
  ) async {
    try {
      // Get current product
      final response =
          await _supabase
              .from('pre_all_products')
              .select('uprices')
              .eq('id', productId)
              .single();

      final currentUPrices = response['uprices'] as String?;
      if (currentUPrices == null ||
          currentUPrices.isEmpty ||
          currentUPrices == 'null') {
        print('Product $productId has no valid uprices data');
        return;
      }

      final List<dynamic> priceList = jsonDecode(currentUPrices);

      // Find the specific price item and add stock type
      bool found = false;

      if (stockType == 'sole_stock') {
        // For sole_stock, add it to ALL elements in the price list
        for (var priceItem in priceList) {
          priceItem[stockType] = '0'; // Initialize with 0
        }
        found = true; // Set found to true since we're updating all items
        print('Added $stockType to ALL price items in product $productId');
      } else {
        // For global_stock, only add to the specific item
        for (var priceItem in priceList) {
          final priceItemId = priceItem['id']?.toString();
          print(
            'Checking priceItem id: $priceItemId against uPriceId: $uPriceId',
          );
          if (priceItemId == uPriceId) {
            priceItem[stockType] = '0'; // Initialize with 0
            print(
              'Added $stockType to price item $priceItemId in product $productId',
            );
            found = true;
            break;
          }
        }
      }

      if (!found) {
        throw Exception(
          'Price item with ID $uPriceId not found in product $productId',
        );
      }

      // Update the product in the database
      final updatedUPrices = jsonEncode(priceList);
      await _supabase
          .from('pre_all_products')
          .update({'uprices': updatedUPrices})
          .eq('id', productId)
          .select()
          .single();

      print(
        'Successfully added $stockType to product $productId, price item $uPriceId',
      );
    } catch (e) {
      print('Error adding stock type to product: $e');
      throw Exception('Failed to add stock type to product: $e');
    }
  }
}

/// Stock type selection dialog
class StockTypeSelectionDialog extends StatelessWidget {
  final String productName;
  final int productId;
  final String uPriceId;
  final VoidCallback onGlobalStockSelected;
  final VoidCallback onSoleStockSelected;

  const StockTypeSelectionDialog({
    Key? key,
    required this.productName,
    required this.productId,
    required this.uPriceId,
    required this.onGlobalStockSelected,
    required this.onSoleStockSelected,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Row(
        children: [
          Icon(Icons.inventory, color: Colors.blue, size: 24),
          SizedBox(width: 8),
          Text('Choose Stock Type'),
        ],
      ),
      content: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'This is the first time adding stock for:',
            style: TextStyle(fontSize: 16, color: Colors.grey.shade600),
          ),
          const SizedBox(height: 8),
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: Colors.blue.shade50,
              borderRadius: BorderRadius.circular(8),
              border: Border.all(color: Colors.blue.shade200),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  productName,
                  style: const TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 14,
                  ),
                ),
                const SizedBox(height: 4),
                Text('Product ID: $productId'),
                Text('Price Variant ID: $uPriceId'),
              ],
            ),
          ),
          const SizedBox(height: 16),
          const Text(
            'Please select how you want to track stock for this product:',
            style: TextStyle(fontSize: 14, fontWeight: FontWeight.w500),
          ),
          const SizedBox(height: 12),
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: Colors.green.shade50,
              borderRadius: BorderRadius.circular(8),
              border: Border.all(color: Colors.green.shade200),
            ),
            child: const Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    Icon(Icons.public, color: Colors.green, size: 16),
                    SizedBox(width: 6),
                    Text(
                      'Global Stock',
                      style: TextStyle(fontWeight: FontWeight.bold),
                    ),
                  ],
                ),
                SizedBox(height: 4),
                Text(
                  'Track total combined stock across all locations/batches',
                  style: TextStyle(fontSize: 12),
                ),
              ],
            ),
          ),
          const SizedBox(height: 8),
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: Colors.orange.shade50,
              borderRadius: BorderRadius.circular(8),
              border: Border.all(color: Colors.orange.shade200),
            ),
            child: const Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    Icon(Icons.inventory_2, color: Colors.orange, size: 16),
                    SizedBox(width: 6),
                    Text(
                      'Sole Stock',
                      style: TextStyle(fontWeight: FontWeight.bold),
                    ),
                  ],
                ),
                SizedBox(height: 4),
                Text(
                  'Track individual stock entries separately by supplier/batch',
                  style: TextStyle(fontSize: 12),
                ),
              ],
            ),
          ),
        ],
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.of(context).pop(),
          child: const Text('Cancel'),
        ),
        ElevatedButton.icon(
          onPressed: () {
            Navigator.of(context).pop();
            onGlobalStockSelected();
          },
          icon: const Icon(Icons.public, size: 16),
          label: const Text('Global Stock'),
          style: ElevatedButton.styleFrom(
            backgroundColor: Colors.green,
            foregroundColor: Colors.white,
          ),
        ),
        ElevatedButton.icon(
          onPressed: () {
            Navigator.of(context).pop();
            onSoleStockSelected();
          },
          icon: const Icon(Icons.inventory_2, size: 16),
          label: const Text('Sole Stock'),
          style: ElevatedButton.styleFrom(
            backgroundColor: Colors.orange,
            foregroundColor: Colors.white,
          ),
        ),
      ],
    );
  }
}

/// Handler class for product details button clicks
class ProductDetailsButtonHandler {
  /// Handle button click for a specific price variant
  static Future<void> handlePriceButtonClick({
    required BuildContext context,
    required int productId,
    required String productName,
    required Map<String, dynamic> priceItem,
    required int priceIndex,
    required Function(List<ProductDetails>) onDataFetched,
    required Function(String) onError,
    VoidCallback? onStockTypeAdded,
  }) async {
    try {
      // Extract the ID from the price item (if it exists)
      final String uPriceId =
          priceItem['id']?.toString() ?? (priceIndex + 1).toString();

      // Generate composite ID
      final String compositeId = ProductDetailsService.generateCompositeId(
        productId,
        uPriceId,
      );

      print('Button clicked for product: $productName');
      print('Product ID: $productId');
      print('uPrice ID: $uPriceId');
      print('Composite ID: $compositeId');
      print('Price Item: $priceItem');

      // Check if any product details exist for this product ID
      final bool hasExistingDetails =
          await ProductDetailsService.hasProductDetailsForProductId(productId);

      if (!hasExistingDetails) {
        // Check if the price item already has stock type attributes
        final bool hasGlobalStock = priceItem.containsKey('global_stock');
        final bool hasSoleStock = priceItem.containsKey('sole_stock');

        if (!hasGlobalStock && !hasSoleStock) {
          // Show stock type selection dialog
          await showDialog(
            context: context,
            barrierDismissible: false,
            builder: (BuildContext dialogContext) {
              return StockTypeSelectionDialog(
                productName: productName,
                productId: productId,
                uPriceId: uPriceId,
                onGlobalStockSelected: () async {
                  try {
                    await ProductDetailsService.addStockTypeToProduct(
                      productId,
                      uPriceId,
                      'global_stock',
                    );
                    if (onStockTypeAdded != null) {
                      onStockTypeAdded();
                    }
                    ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(
                        content: Text(
                          'Global stock tracking enabled for this product',
                        ),
                        backgroundColor: Colors.green,
                      ),
                    );
                  } catch (e) {
                    onError('Failed to set global stock type: $e');
                  }
                },
                onSoleStockSelected: () async {
                  try {
                    await ProductDetailsService.addStockTypeToProduct(
                      productId,
                      uPriceId,
                      'sole_stock',
                    );
                    if (onStockTypeAdded != null) {
                      onStockTypeAdded();
                    }
                    ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(
                        content: Text(
                          'Sole stock tracking enabled for this product',
                        ),
                        backgroundColor: Colors.orange,
                      ),
                    );
                  } catch (e) {
                    onError('Failed to set sole stock type: $e');
                  }
                },
              );
            },
          );

          // After stock type is set, we don't proceed to show the details dialog yet
          // The user needs to click again to actually manage stock
          return;
        }
      }

      // Fetch product details from Supabase
      final List<ProductDetails> productDetailsList =
          await ProductDetailsService.getProductDetailsByCompositeId(
            compositeId,
          );

      if (productDetailsList.isNotEmpty) {
        print('Found ${productDetailsList.length} product details:');
        for (final detail in productDetailsList) {
          print('  - $detail');
        }
        onDataFetched(productDetailsList);
      } else {
        print('No product details found for composite ID: $compositeId');
        onDataFetched([]);
      }
    } catch (error) {
      print('Error handling price button click: $error');
      onError('Failed to fetch product details: $error');
    }
  }

  /// Show product details in a dialog
  static Future<void> showProductDetailsDialog({
    required context,
    required String productName,
    required String compositeId,
    required List<ProductDetails> productDetailsList,
    VoidCallback? onStockUpdated,
  }) {
    return showDialog(
      context: context,
      builder: (BuildContext context) {
        return ProductDetailsDialog(
          productName: productName,
          compositeId: compositeId,
          productDetailsList: productDetailsList,
          onStockUpdated: onStockUpdated,
        );
      },
    );
  }
}

/// Stateful widget for product details dialog with add/edit functionality
class ProductDetailsDialog extends StatefulWidget {
  final String productName;
  final String compositeId;
  final List<ProductDetails> productDetailsList;
  final VoidCallback? onStockUpdated;

  const ProductDetailsDialog({
    Key? key,
    required this.productName,
    required this.compositeId,
    required this.productDetailsList,
    this.onStockUpdated,
  }) : super(key: key);

  @override
  _ProductDetailsDialogState createState() => _ProductDetailsDialogState();
}

class _ProductDetailsDialogState extends State<ProductDetailsDialog> {
  late List<ProductDetails> _productDetailsList;
  List<int> _editingRows = [];
  int? _newRowIndex;

  // Controllers for new row inputs
  final _quantityController = TextEditingController();
  final _unitController = TextEditingController();
  final _priceController = TextEditingController();
  final _supplierController = TextEditingController();
  final _expireDateController = TextEditingController();

  // Controllers for editing existing rows
  Map<int, Map<String, TextEditingController>> _editControllers = {};

  @override
  void initState() {
    super.initState();
    _productDetailsList = List.from(widget.productDetailsList);
    // Sort by created_at to ensure ascending order
    _productDetailsList.sort((a, b) => a.createdAt.compareTo(b.createdAt));
  }

  @override
  void dispose() {
    _quantityController.dispose();
    _unitController.dispose();
    _priceController.dispose();
    _supplierController.dispose();
    _expireDateController.dispose();

    // Dispose edit controllers
    for (var controllers in _editControllers.values) {
      for (var controller in controllers.values) {
        controller.dispose();
      }
    }
    super.dispose();
  }

  /// Update the stock attribute in the product's uPrices JSON
  Future<void> _updateProductStock(
    int productId,
    String uPriceId,
    int quantityToAdd,
  ) async {
    try {
      print(
        'Attempting to update stock for product $productId, uPrice $uPriceId, quantity change: $quantityToAdd',
      );

      // First check if the product exists
      final existsResponse = await Supabase.instance.client
          .from('pre_all_products')
          .select('id')
          .eq('id', productId);

      if (existsResponse.isEmpty) {
        throw Exception(
          'Product with ID $productId does not exist in pre_all_products table',
        );
      }

      // Get current product data
      final response =
          await Supabase.instance.client
              .from('pre_all_products')
              .select('uprices')
              .eq('id', productId)
              .single();

      final currentUPrices = response['uprices'] as String?;
      if (currentUPrices == null ||
          currentUPrices.isEmpty ||
          currentUPrices == 'null') {
        print('Product $productId has no valid uprices data');
        return;
      }

      // Parse the current uPrices JSON
      final List<dynamic> priceList = jsonDecode(currentUPrices);

      // Find the specific price item and update its stock
      bool found = false;
      for (var priceItem in priceList) {
        if (priceItem['id']?.toString() == uPriceId) {
          // Determine which stock type to update based on existing attributes
          if (priceItem.containsKey('global_stock')) {
            // Update global stock
            final currentStock =
                priceItem['global_stock'] != null
                    ? int.tryParse(priceItem['global_stock'].toString()) ?? 0
                    : 0;
            priceItem['global_stock'] =
                (currentStock + quantityToAdd).toString();
            print(
              'Updated global_stock for product $productId, uPrice $uPriceId: ${priceItem['global_stock']}',
            );
          } else if (priceItem.containsKey('sole_stock')) {
            // Update sole stock
            final currentStock =
                priceItem['sole_stock'] != null
                    ? int.tryParse(priceItem['sole_stock'].toString()) ?? 0
                    : 0;
            priceItem['sole_stock'] = (currentStock + quantityToAdd).toString();
            print(
              'Updated sole_stock for product $productId, uPrice $uPriceId: ${priceItem['sole_stock']}',
            );
          } else {
            // Legacy support: if neither stock type is defined, use 'stock' attribute
            final currentStock =
                priceItem['stock'] != null
                    ? int.tryParse(priceItem['stock'].toString()) ?? 0
                    : 0;
            priceItem['stock'] = (currentStock + quantityToAdd).toString();
            print(
              'Updated legacy stock for product $productId, uPrice $uPriceId: ${priceItem['stock']}',
            );
          }
          found = true;
          break;
        }
      }

      if (!found) {
        throw Exception(
          'Price item with ID $uPriceId not found in product $productId',
        );
      }

      // Convert back to JSON string
      final updatedUPrices = jsonEncode(priceList);

      // Update the product in the database
      final updateResponse = await Supabase.instance.client
          .from('pre_all_products')
          .update({'uprices': updatedUPrices})
          .eq('id', productId);

      print(
        'Successfully updated stock for product $productId, price item $uPriceId. Update response: $updateResponse',
      );
    } catch (e) {
      print(
        'Error updating product stock for product $productId, uPrice $uPriceId: $e',
      );
      if (e.toString().contains('multiple (or no) rows returned')) {
        print('Product $productId not found in pre_all_products table');
        throw Exception(
          'Product $productId not found in database. Please check if the product exists.',
        );
      }
      throw Exception('Failed to update product stock: $e');
    }
  }

  void _addNewRow() {
    setState(() {
      _newRowIndex = _productDetailsList.length;
      _quantityController.clear();
      _unitController.clear();
      _priceController.clear();
      _supplierController.clear();
      _expireDateController.clear();
    });
  }

  void _cancelNewRow() {
    setState(() {
      _newRowIndex = null;
    });
  }

  void _saveNewRow() async {
    if (_validateNewRowInputs()) {
      try {
        final newQuantity = int.parse(_quantityController.text);

        // Parse composite ID to get product ID and price item ID
        final compositeIdParts = ProductDetailsService.parseCompositeId(
          widget.compositeId,
        );
        final productId = compositeIdParts['productId'];
        final uPriceId = compositeIdParts['uPriceId'];

        // Try to update stock in product's uPrices before saving product details
        try {
          await _updateProductStock(productId, uPriceId, newQuantity);
        } catch (e) {
          // If the product doesn't exist in all_products table, log warning but continue
          print('Warning: Could not update stock in all_products table: $e');
          print('Continuing with product detail creation...');
        }

        final newDetail = ProductDetails(
          id: 0, // Will be auto-generated by database
          identityId: widget.compositeId,
          createdAt: DateTime.now(),
          quantity: newQuantity,
          unit: _unitController.text,
          price: double.tryParse(_priceController.text) ?? 0.0,
          supplier: _supplierController.text,
          expireDate: DateTime.parse(_expireDateController.text),
        );

        // Save to database
        await ProductDetailsService.createProductDetail(newDetail);

        // Refresh the list
        final updatedList =
            await ProductDetailsService.getProductDetailsByCompositeId(
              widget.compositeId,
            );

        setState(() {
          _productDetailsList = updatedList;
          // Sort by created_at to maintain ascending order
          _productDetailsList.sort(
            (a, b) => a.createdAt.compareTo(b.createdAt),
          );
          _newRowIndex = null;
        });

        // Notify parent about stock update with a small delay to ensure DB consistency
        if (widget.onStockUpdated != null) {
          // Add a small delay to ensure the database update is fully committed
          await Future.delayed(const Duration(milliseconds: 100));
          widget.onStockUpdated!();
        }

        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Product detail added successfully')),
        );
      } catch (e) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error adding product detail: $e')),
        );
      }
    }
  }

  bool _validateNewRowInputs() {
    if (_quantityController.text.isEmpty ||
        _unitController.text.isEmpty ||
        _priceController.text.isEmpty ||
        _supplierController.text.isEmpty ||
        _expireDateController.text.isEmpty) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text('Please fill all fields')));
      return false;
    }

    if (int.tryParse(_quantityController.text) == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Quantity must be a valid number')),
      );
      return false;
    }

    if (double.tryParse(_priceController.text) == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Price must be a valid number (e.g. 10.50)'),
        ),
      );
      return false;
    }

    if (DateTime.tryParse(_expireDateController.text) == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Expire date must be in format YYYY-MM-DD'),
        ),
      );
      return false;
    }

    return true;
  }

  void _editRow(int index) {
    final detail = _productDetailsList[index];
    _editControllers[index] = {
      'quantity': TextEditingController(text: detail.quantity.toString()),
      'unit': TextEditingController(text: detail.unit),
      'price': TextEditingController(text: detail.price.toString()),
      'supplier': TextEditingController(text: detail.supplier),
      'expireDate': TextEditingController(
        text: detail.expireDate.toLocal().toString().split(' ')[0],
      ),
    };

    setState(() {
      _editingRows.add(index);
    });
  }

  void _cancelEdit(int index) {
    setState(() {
      _editingRows.remove(index);
      if (_editControllers.containsKey(index)) {
        for (var controller in _editControllers[index]!.values) {
          controller.dispose();
        }
        _editControllers.remove(index);
      }
    });
  }

  void _saveEdit(int index) async {
    final controllers = _editControllers[index]!;

    try {
      final oldQuantity = _productDetailsList[index].quantity;
      final newQuantity = int.parse(controllers['quantity']!.text);
      final quantityDifference = newQuantity - oldQuantity;

      final updatedDetail = ProductDetails(
        id: _productDetailsList[index].id,
        identityId: _productDetailsList[index].identityId,
        createdAt: _productDetailsList[index].createdAt,
        quantity: newQuantity,
        unit: controllers['unit']!.text,
        price: double.tryParse(controllers['price']!.text) ?? 0.0,
        supplier: controllers['supplier']!.text,
        expireDate: DateTime.parse(controllers['expireDate']!.text),
      );

      // Try to update stock if quantity changed
      if (quantityDifference != 0) {
        final compositeIdParts = ProductDetailsService.parseCompositeId(
          widget.compositeId,
        );
        final productId = compositeIdParts['productId'];
        final uPriceId = compositeIdParts['uPriceId'];

        try {
          await _updateProductStock(productId, uPriceId, quantityDifference);
        } catch (e) {
          // If the product doesn't exist in all_products table, log warning but continue
          print('Warning: Could not update stock in all_products table: $e');
          print('Continuing with product detail update...');
        }
      }
      await ProductDetailsService.updateProductDetail(updatedDetail);

      // Refresh the list
      final updatedList =
          await ProductDetailsService.getProductDetailsByCompositeId(
            widget.compositeId,
          );

      setState(() {
        _productDetailsList = updatedList;
        // Sort by created_at to maintain ascending order
        _productDetailsList.sort((a, b) => a.createdAt.compareTo(b.createdAt));
        _editingRows.remove(index);
      });

      // Notify parent about stock update if quantity changed with a delay to ensure DB consistency
      if (quantityDifference != 0 && widget.onStockUpdated != null) {
        // Add a small delay to ensure the database update is fully committed
        await Future.delayed(const Duration(milliseconds: 100));
        widget.onStockUpdated!();
      }

      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Product detail updated successfully')),
      );
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error updating product detail: $e')),
      );
    }
  }

  void _deleteRow(int index) async {
    final productDetail = _productDetailsList[index];

    // Show confirmation dialog
    final bool? shouldDelete = await showDialog<bool>(
      context: context,
      builder: (BuildContext dialogContext) {
        return AlertDialog(
          title: const Row(
            children: [
              Icon(Icons.warning, color: Colors.red, size: 24),
              SizedBox(width: 8),
              Text('Delete Product Detail'),
            ],
          ),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text(
                'Are you sure you want to delete this product detail?',
                style: TextStyle(fontSize: 16),
              ),
              const SizedBox(height: 16),
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: Colors.grey.shade100,
                  borderRadius: BorderRadius.circular(8),
                  border: Border.all(color: Colors.grey.shade300),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Identity ID: ${productDetail.identityId}',
                      style: const TextStyle(fontWeight: FontWeight.bold),
                    ),
                    const SizedBox(height: 4),
                    Text('Quantity: ${productDetail.quantity}'),
                    Text('Unit: ${productDetail.unit}'),
                    Text('Price: ${productDetail.price}'),
                    Text('Supplier: ${productDetail.supplier}'),
                    Text(
                      'Expire Date: ${productDetail.expireDate.toLocal().toString().split(' ')[0]}',
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 16),
              const Text(
                'This action cannot be undone.',
                style: TextStyle(
                  color: Colors.red,
                  fontWeight: FontWeight.w500,
                ),
              ),
            ],
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.of(dialogContext).pop(false),
              child: const Text('Cancel'),
            ),
            ElevatedButton(
              onPressed: () => Navigator.of(dialogContext).pop(true),
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.red,
                foregroundColor: Colors.white,
              ),
              child: const Text('Delete'),
            ),
          ],
        );
      },
    );

    // Only proceed with deletion if user confirmed
    if (shouldDelete == true) {
      try {
        final deletedQuantity = productDetail.quantity;

        // Try to update stock by reducing the deleted quantity
        final compositeIdParts = ProductDetailsService.parseCompositeId(
          widget.compositeId,
        );
        final productId = compositeIdParts['productId'];
        final uPriceId = compositeIdParts['uPriceId'];

        try {
          await _updateProductStock(productId, uPriceId, -deletedQuantity);
        } catch (e) {
          // If the product doesn't exist in all_products table, just log and continue
          // The product detail can still be deleted from products_details table
          print('Warning: Could not update stock in all_products table: $e');
          print('Continuing with product detail deletion...');
        }

        await ProductDetailsService.deleteProductDetail(
          _productDetailsList[index].id,
        );

        // Refresh the list
        final updatedList =
            await ProductDetailsService.getProductDetailsByCompositeId(
              widget.compositeId,
            );

        setState(() {
          _productDetailsList = updatedList;
          // Sort by created_at to maintain ascending order
          _productDetailsList.sort(
            (a, b) => a.createdAt.compareTo(b.createdAt),
          );
        });

        // Notify parent about stock update with a delay to ensure DB consistency
        if (widget.onStockUpdated != null) {
          // Add a small delay to ensure the database update is fully committed
          await Future.delayed(const Duration(milliseconds: 100));
          widget.onStockUpdated!();
        }

        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Product detail deleted successfully')),
        );
      } catch (e) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error deleting product detail: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: Text('Product Details - ${widget.productName}'),
      content: SizedBox(
        width: double.maxFinite,
        height: 600,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            SelectableText(
              'Composite ID: ${widget.compositeId}',
              style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14),
            ),
            const SizedBox(height: 16),
            Row(
              children: [
                ElevatedButton.icon(
                  onPressed: _newRowIndex == null ? _addNewRow : null,
                  icon: const Icon(Icons.add),
                  label: const Text('Add Product Details'),
                ),
              ],
            ),
            const SizedBox(height: 16),
            Expanded(
              child: SingleChildScrollView(
                child: Table(
                  border: TableBorder.all(
                    color: Colors.grey.shade400,
                    width: 1,
                  ),
                  columnWidths: const {
                    0: FlexColumnWidth(1), // ID
                    1: FlexColumnWidth(1.5), // Identity ID
                    2: FlexColumnWidth(1.2), // Quantity
                    3: FlexColumnWidth(1), // Unit
                    4: FlexColumnWidth(1.2), // Price
                    5: FlexColumnWidth(1.5), // Supplier
                    6: FlexColumnWidth(1.5), // Expire Date
                    7: FlexColumnWidth(2), // Created At
                    8: FlexColumnWidth(2), // Actions
                  },
                  children: [
                    // Header row
                    TableRow(
                      decoration: BoxDecoration(color: Colors.grey.shade200),
                      children: const [
                        TableCell(
                          child: Padding(
                            padding: EdgeInsets.all(8.0),
                            child: Text(
                              'ID',
                              style: TextStyle(
                                fontWeight: FontWeight.bold,
                                fontSize: 14,
                              ),
                            ),
                          ),
                        ),
                        TableCell(
                          child: Padding(
                            padding: EdgeInsets.all(8.0),
                            child: Text(
                              'Identity ID',
                              style: TextStyle(
                                fontWeight: FontWeight.bold,
                                fontSize: 14,
                              ),
                            ),
                          ),
                        ),
                        TableCell(
                          child: Padding(
                            padding: EdgeInsets.all(8.0),
                            child: Text(
                              'Quantity',
                              style: TextStyle(
                                fontWeight: FontWeight.bold,
                                fontSize: 14,
                              ),
                            ),
                          ),
                        ),
                        TableCell(
                          child: Padding(
                            padding: EdgeInsets.all(8.0),
                            child: Text(
                              'Unit',
                              style: TextStyle(
                                fontWeight: FontWeight.bold,
                                fontSize: 14,
                              ),
                            ),
                          ),
                        ),
                        TableCell(
                          child: Padding(
                            padding: EdgeInsets.all(8.0),
                            child: Text(
                              'Price',
                              style: TextStyle(
                                fontWeight: FontWeight.bold,
                                fontSize: 14,
                              ),
                            ),
                          ),
                        ),
                        TableCell(
                          child: Padding(
                            padding: EdgeInsets.all(8.0),
                            child: Text(
                              'Supplier',
                              style: TextStyle(
                                fontWeight: FontWeight.bold,
                                fontSize: 14,
                              ),
                            ),
                          ),
                        ),
                        TableCell(
                          child: Padding(
                            padding: EdgeInsets.all(8.0),
                            child: Text(
                              'Expire Date',
                              style: TextStyle(
                                fontWeight: FontWeight.bold,
                                fontSize: 14,
                              ),
                            ),
                          ),
                        ),
                        TableCell(
                          child: Padding(
                            padding: EdgeInsets.all(8.0),
                            child: Text(
                              'Created At',
                              style: TextStyle(
                                fontWeight: FontWeight.bold,
                                fontSize: 14,
                              ),
                            ),
                          ),
                        ),
                        TableCell(
                          child: Padding(
                            padding: EdgeInsets.all(8.0),
                            child: Text(
                              'Actions',
                              style: TextStyle(
                                fontWeight: FontWeight.bold,
                                fontSize: 14,
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                    // Data rows
                    ..._productDetailsList.asMap().entries.map((entry) {
                      final index = entry.key;
                      final detail = entry.value;
                      final isEditing = _editingRows.contains(index);

                      return TableRow(
                        children: [
                          TableCell(
                            child: Padding(
                              padding: const EdgeInsets.all(8.0),
                              child: SelectableText(
                                detail.id.toString(),
                                style: const TextStyle(fontSize: 13),
                              ),
                            ),
                          ),
                          TableCell(
                            child: Padding(
                              padding: const EdgeInsets.all(8.0),
                              child: SelectableText(
                                detail.identityId,
                                style: const TextStyle(fontSize: 13),
                              ),
                            ),
                          ),
                          TableCell(
                            child: Padding(
                              padding: const EdgeInsets.all(4.0),
                              child:
                                  isEditing
                                      ? TextField(
                                        controller:
                                            _editControllers[index]!['quantity'],
                                        style: const TextStyle(fontSize: 13),
                                        decoration: const InputDecoration(
                                          border: OutlineInputBorder(),
                                          isDense: true,
                                        ),
                                      )
                                      : SelectableText(
                                        detail.quantity.toString(),
                                        style: const TextStyle(fontSize: 13),
                                      ),
                            ),
                          ),
                          TableCell(
                            child: Padding(
                              padding: const EdgeInsets.all(4.0),
                              child:
                                  isEditing
                                      ? TextField(
                                        controller:
                                            _editControllers[index]!['unit'],
                                        style: const TextStyle(fontSize: 13),
                                        decoration: const InputDecoration(
                                          border: OutlineInputBorder(),
                                          isDense: true,
                                        ),
                                      )
                                      : SelectableText(
                                        detail.unit,
                                        style: const TextStyle(fontSize: 13),
                                      ),
                            ),
                          ),
                          TableCell(
                            child: Padding(
                              padding: const EdgeInsets.all(4.0),
                              child:
                                  isEditing
                                      ? TextField(
                                        controller:
                                            _editControllers[index]!['price'],
                                        style: const TextStyle(fontSize: 13),
                                        decoration: const InputDecoration(
                                          border: OutlineInputBorder(),
                                          isDense: true,
                                        ),
                                      )
                                      : SelectableText(
                                        detail.price.toString(),
                                        style: const TextStyle(fontSize: 13),
                                      ),
                            ),
                          ),
                          TableCell(
                            child: Padding(
                              padding: const EdgeInsets.all(4.0),
                              child:
                                  isEditing
                                      ? TextField(
                                        controller:
                                            _editControllers[index]!['supplier'],
                                        style: const TextStyle(fontSize: 13),
                                        decoration: const InputDecoration(
                                          border: OutlineInputBorder(),
                                          isDense: true,
                                        ),
                                      )
                                      : SelectableText(
                                        detail.supplier,
                                        style: const TextStyle(fontSize: 13),
                                      ),
                            ),
                          ),
                          TableCell(
                            child: Padding(
                              padding: const EdgeInsets.all(4.0),
                              child:
                                  isEditing
                                      ? TextField(
                                        controller:
                                            _editControllers[index]!['expireDate'],
                                        style: const TextStyle(fontSize: 13),
                                        decoration: const InputDecoration(
                                          border: OutlineInputBorder(),
                                          isDense: true,
                                          hintText: 'YYYY-MM-DD',
                                        ),
                                      )
                                      : SelectableText(
                                        detail.expireDate
                                            .toLocal()
                                            .toString()
                                            .split(' ')[0],
                                        style: const TextStyle(fontSize: 13),
                                      ),
                            ),
                          ),
                          TableCell(
                            child: Padding(
                              padding: const EdgeInsets.all(8.0),
                              child: SelectableText(
                                detail.createdAt.toLocal().toString(),
                                style: const TextStyle(fontSize: 13),
                              ),
                            ),
                          ),
                          TableCell(
                            child: Padding(
                              padding: const EdgeInsets.all(4.0),
                              child:
                                  isEditing
                                      ? Row(
                                        mainAxisSize: MainAxisSize.min,
                                        children: [
                                          IconButton(
                                            onPressed: () => _saveEdit(index),
                                            icon: const Icon(
                                              Icons.save,
                                              size: 16,
                                            ),
                                            tooltip: 'Save',
                                          ),
                                          IconButton(
                                            onPressed: () => _cancelEdit(index),
                                            icon: const Icon(
                                              Icons.cancel,
                                              size: 16,
                                            ),
                                            tooltip: 'Cancel',
                                          ),
                                        ],
                                      )
                                      : Row(
                                        mainAxisSize: MainAxisSize.min,
                                        children: [
                                          IconButton(
                                            onPressed: () => _editRow(index),
                                            icon: const Icon(
                                              Icons.edit,
                                              size: 16,
                                            ),
                                            tooltip: 'Edit',
                                          ),
                                          IconButton(
                                            onPressed: () => _deleteRow(index),
                                            icon: const Icon(
                                              Icons.delete,
                                              size: 16,
                                            ),
                                            tooltip: 'Delete',
                                          ),
                                        ],
                                      ),
                            ),
                          ),
                        ],
                      );
                    }).toList(),
                    // New row for adding data
                    if (_newRowIndex != null)
                      TableRow(
                        decoration: BoxDecoration(color: Colors.blue.shade50),
                        children: [
                          const TableCell(
                            child: Padding(
                              padding: EdgeInsets.all(8.0),
                              child: Text(
                                'New',
                                style: TextStyle(
                                  fontSize: 13,
                                  fontStyle: FontStyle.italic,
                                ),
                              ),
                            ),
                          ),
                          TableCell(
                            child: Padding(
                              padding: const EdgeInsets.all(8.0),
                              child: SelectableText(
                                widget.compositeId,
                                style: const TextStyle(
                                  fontSize: 13,
                                  fontStyle: FontStyle.italic,
                                ),
                              ),
                            ),
                          ),
                          TableCell(
                            child: Padding(
                              padding: const EdgeInsets.all(4.0),
                              child: TextField(
                                controller: _quantityController,
                                style: const TextStyle(fontSize: 13),
                                decoration: const InputDecoration(
                                  border: OutlineInputBorder(),
                                  isDense: true,
                                  hintText: 'Quantity',
                                ),
                              ),
                            ),
                          ),
                          TableCell(
                            child: Padding(
                              padding: const EdgeInsets.all(4.0),
                              child: TextField(
                                controller: _unitController,
                                style: const TextStyle(fontSize: 13),
                                decoration: const InputDecoration(
                                  border: OutlineInputBorder(),
                                  isDense: true,
                                  hintText: 'Unit',
                                ),
                              ),
                            ),
                          ),
                          TableCell(
                            child: Padding(
                              padding: const EdgeInsets.all(4.0),
                              child: TextField(
                                controller: _priceController,
                                style: const TextStyle(fontSize: 13),
                                decoration: const InputDecoration(
                                  border: OutlineInputBorder(),
                                  isDense: true,
                                  hintText: 'Price',
                                ),
                              ),
                            ),
                          ),
                          TableCell(
                            child: Padding(
                              padding: const EdgeInsets.all(4.0),
                              child: TextField(
                                controller: _supplierController,
                                style: const TextStyle(fontSize: 13),
                                decoration: const InputDecoration(
                                  border: OutlineInputBorder(),
                                  isDense: true,
                                  hintText: 'Supplier',
                                ),
                              ),
                            ),
                          ),
                          TableCell(
                            child: Padding(
                              padding: const EdgeInsets.all(4.0),
                              child: TextField(
                                controller: _expireDateController,
                                style: const TextStyle(fontSize: 13),
                                decoration: const InputDecoration(
                                  border: OutlineInputBorder(),
                                  isDense: true,
                                  hintText: 'YYYY-MM-DD',
                                ),
                              ),
                            ),
                          ),
                          const TableCell(
                            child: Padding(
                              padding: EdgeInsets.all(8.0),
                              child: Text(
                                'Now',
                                style: TextStyle(
                                  fontSize: 13,
                                  fontStyle: FontStyle.italic,
                                ),
                              ),
                            ),
                          ),
                          TableCell(
                            child: Padding(
                              padding: const EdgeInsets.all(4.0),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                children: [
                                  IconButton(
                                    onPressed: _saveNewRow,
                                    icon: const Icon(Icons.save, size: 16),
                                    tooltip: 'Save',
                                  ),
                                  IconButton(
                                    onPressed: _cancelNewRow,
                                    icon: const Icon(Icons.cancel, size: 16),
                                    tooltip: 'Cancel',
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ],
                      ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
      actions: [
        TextButton(
          onPressed: () {
            Navigator.of(context).pop();
          },
          child: const Text('Close'),
        ),
      ],
    );
  }
}
